### ISSUE TITLE
error in rye.R --eigenval=1240k279popsadmixture_pca.eigenval --eigenvec=1240k279popsadmixture_pca.eigenvec --pop2group=pop_group --threads=10 --output=1240k279popsadmixturerye_output

### ISSUE THREAD

**Issue by GuanglinHe1** [healthdisparities/rye#6]
Dear Lavanya, i prepared the all files and run it and following errors occurred. Would you give me some advice.

Error in params[[bestError]] : 
  attempt to select less than one element in get1index
Calls: rye -> rye.optimize

**Comment by AaronRuben** [comment]
I got the same error. Make sure your pop2group.txt has the two columns **Pop** and **Group**. The capitalization is important. That solved it for me.

**Comment by Taghrid-M** [comment]
I'm facing the same issue, and I've double-checked my pop2group.txt file – the columns 'Pop' and 'Group' are indeed capitalized. Could you possibly help me figure this out?

[ Mar 09 2024 - 10:38:43 PM ] Parsing user supplied arguments...
[ Mar 09 2024 - 10:38:44 PM ] Arguments passed validation
[ Mar 09 2024 - 10:38:44 PM ] Running core rye with 2 threads
[ Mar 09 2024 - 10:38:44 PM ] Reading in Eigenvector file
[ Mar 09 2024 - 10:38:44 PM ] Reading in Eigenvalue file
[ Mar 09 2024 - 10:38:44 PM ] Reading in pop2group file
[ Mar 09 2024 - 10:38:44 PM ] Creating individual mapping
[ Mar 09 2024 - 10:38:44 PM ] Scaling PCs
[ Mar 09 2024 - 10:38:44 PM ] Weighting PCs
[ Mar 09 2024 - 10:38:44 PM ] Aggregating individuals to population groups
[ Mar 09 2024 - 10:38:44 PM ] Optimizing estimates using NNLS
Round 1/5 Mean error: NA, Best error:
Error in params[[bestError]] :
  attempt to select less than one element in get1index
Calls: rye -> rye.optimize
In addition: Warning messages:
1: In mclapply(seq(attempts), function(i) rye.gibbs(X = referenceX,  :
  all scheduled cores encountered errors in user code
2: In which.min(errors) : NAs introduced by coercion
3: In mean.default(errors) :
  argument is not numeric or logical: returning NA
Execution halted

Many thanks,
Taghrid
